export const ADD_SEASON_TOPIC_REQUEST     = 'ADD_SEASON_TOPIC_REQUEST';
export const ADD_SEASON_TOPIC_SUCCESS     = 'ADD_SEASON_TOPIC_SUCCESS';
export const ADD_SEASON_TOPIC_FAIL        = 'ADD_SEASON_TOPIC_FAIL';