export const GET_POST_REQUEST = 'GET_POST_REQUEST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_FAIL = 'GET_POST_FAIL';

export const GET_POST_LIKESTATE_REQUEST = 'GET_POST_LIKESTATE_REQUEST';
export const GET_POST_LIKESTATE_SUCCESS = 'GET_POST_LIKESTATE_SUCCESS';
export const GET_POST_LIKESTATE_FAIL = 'GET_POST_LIKESTATE_FAIL';

export const POST_LIKES_REQUEST = 'POST_LIKES_REQUEST';
export const POST_LIKES_SUCCESS = 'POST_LIKES_SUCCESS';
export const POST_LIKES_FAIL = 'POST_LIKES_FAIL';