export const RECOVER_PASS_FROM_EMAIL_REQUEST     = 'USER_RECOVER_EMAIL_REQUEST';
export const RECOVER_PASS_FROM_EMAIL_SUCCESS     = 'RECOVER_PASS_FROM_EMAIL_SUCCESS';
export const RECOVER_PASS_FROM_EMAIL_FAIL        = 'RECOVER_PASS_FROM_EMAIL_FAIL';