export const STATISTIC_REQUEST_SUCCESS = 'STATISTIC_REQUEST_SUCESS';
export const STATISTIC_REQUEST_FAIL = 'STATISTIC_REQUEST_FAIL';
export const STATISTIC_REQUEST_REQUEST = 'STATISTIC_REQUEST_REQUEST';
export const STATISTIC_REQUEST_RESET = 'STATISTIC_REQUEST_RESET';