export const USER_LOGIN_REQUEST     = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS     = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL        = 'USER_LOGIN_FAIL';
export const USER_LOGOUT            = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST     = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS     = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL        = 'USER_REGISTER_FAIL';

export const USER_RECOVER_EMAIL_REQUEST     = 'USER_RECOVER_EMAIL_REQUEST';
export const USER_RECOVER_EMAIL_SUCCESS     = 'USER_RECOVER_EMAIL_SUCCESS';
export const USER_RECOVER_EMAIL_FAIL        = 'USER_RECOVER_EMAIL_FAIL';

export const USER_GETALL_REQUEST     = 'USER_GETALL_REQUEST';
export const USER_GETALL_SUCCESS     = 'USER_GETALL_SUCCESS';
export const USER_GETALL_FAIL        = 'USER_GETALL_FAIL';

export const USER_DELETE_DEPARTMENT_REQUEST     = 'USER_DELETE_DEPARTMENT_REQUEST';
export const USER_DELETE_DEPARTMENT_SUCCESS     = 'USER_DELETE_DEPARTMENT_SUCCESS';
export const USER_DELETE_DEPARTMENT_FAIL        = 'USER_DELETE_DEPARTMENT_FAIL';
