GET http://localhost:5001/api/auth/register

################################

//Get all Article. get specific one with query ?creator=(insert email), ?session=(insert session), ?userId=(insert user ID) and ?topic=(insert topic)
GET http://localhost:5001/api/article/getAll_Article

################################

//Get all Session
GET http://localhost:5001/api/session/getAll_Session

################################

//Count All Article
GET http://localhost:5001/api/article/countAll

################################

//Count All Article with faculty with query api?faculty=(insert faculty)
GET http://localhost:5001/api/article/countWith_faculty?faculty=IT

################################

//Count All User submitted Article
GET http://localhost:5001/api/user/userWithArticle

################################

//Count All User submitted Article of an Faculty
GET http://localhost:5001/api/user/count_userFaculty_haveArticle?faculty=Marketing

################################

//Count All User sort with faculty and role using ?name=(insert) or search same with ?name=(insert)&name=(insert)
GET http://localhost:5001/api/user/getAll_user?faculty=Design&role=manager

################################

//Update article status with article ID
PUT http://localhost:5001/api/article/status/6118d4012ec0a91ca0121a34
Content-Type: application/json

{
    "status": true
}

################################

//Update session information with ID
PUT http://localhost:5001/api/session/edit/611769f3abda6b0f648b9ec5
Content-Type: application/json

{
    "topic": "Qwerty",
    "startedDate" : "10/20/2021"
}

################################

//register a new user for admin
POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
    "email" : "longnh20072000@gmail.com",
    "password" : "Longdeptrai123",
    "faculty" : "Marketing",
    "role" : "student"
}

################################

//User Login
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
    "email" : "ltv.9a2.21@gmail.com",
    "password" : "Longdeptrai123"
}

################################

// Create Article
POST http://localhost:5001/api/article/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE0Y2M4YTg5NGQ4NTUxMTAwNDFkNzQiLCJlbWFpbCI6Imx0di45YTIuMjFAZ21haWwuY29tIiwiZmFjdWx0eSI6IklUIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjI5MDE3MDcyLCJleHAiOjE2MjkwMTg4NzJ9.PN06B5hZ44HVs6dfwG5BAKEtrktLJ7bf4I9Q8-m9ibw

{
    "title" : "This is a Test about session",
    "description" : "Add Session automatically from Session model",
    "type" : "Testing API Article"
}

################################

//Add comment in Article
POST http://localhost:5001/api/article/add_comment
Content-Type: application/json

{
    "articleId" : "6114d5f6c7e3375c7892f2a2",
    "email" : "longnh20072000@gmail.com",
    "text" : "Sủa"
}

################################

//Create new Session with Token have admin role
POST http://localhost:5001/api/session/add_session
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE0Y2M4YTg5NGQ4NTUxMTAwNDFkNzQiLCJlbWFpbCI6Imx0di45YTIuMjFAZ21haWwuY29tIiwiZmFjdWx0eSI6IklUIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjI4OTI2MjA5LCJleHAiOjE2Mjg5MjgwMDl9.eGvKeOjsFgdyjePnevALDfSjLiuhrzC_R6m_JYFKhsA

{
    "session" : "Winter 2021",
    "startedDate" : "10/1/2021",
    "endedDate" : "12/1/2021",
    "topic" : "Life"
}

################################

//Send mail forgot password
POST http://localhost:5001/api/user/forgotPassword
Content-Type: application/json

{
    "email" : "ltv.9a2.21@gmail.com"
}

################################