GET http://localhost:5001/api/auth/register

################################

//register a new user for admin
POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
    "email" : "longnh20072000@gmail.com",
    "password" : "Longdeptrai123",
    "faculty" : "IT",
    "role" : "admin"
}

################################

//User Login
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
    "email" : "ltv.9a2.21@gmail.com",
    "password" : "Longdeptrai123"
}

################################




















//For testing
POST http://localhost:5001/api/test/createtestuser
Content-Type: application/json

{
    "username" : "ltv.9a2.21@gmail.com",
    "password" : "Longdeptrai123"
}

################################

POST http://localhost:5001/api/test/createpost
Content-Type: application/json

{
    "title" : "Covid 19 is down 2",
    "message" : "The covid is no longer existed 2"
}

################################