GET http://localhost:5001/api/auth/register

################################

//Get all Article. get specific one with query ?creator=(insert email), ?session=(insert session), ?userId=(insert user ID) and ?topic=(insert topic)
GET http://localhost:5001/api/article/getAll_Article

################################

//Get all Session
GET http://localhost:5001/api/session/getAll_Session

################################

//register a new user for admin
POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
    "email" : "ltv.9a2.21@gmail.com",
    "password" : "Longdeptrai123",
    "faculty" : "IT",
    "role" : "admin"
}

################################

//User Login
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
    "email" : "ltv.9a2.21@gmail.com",
    "password" : "Longdeptrai123"
}

################################

// Create Article
POST http://localhost:5001/api/article/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE0Y2M4YTg5NGQ4NTUxMTAwNDFkNzQiLCJlbWFpbCI6Imx0di45YTIuMjFAZ21haWwuY29tIiwiZmFjdWx0eSI6IklUIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjI4OTI2MjA5LCJleHAiOjE2Mjg5MjgwMDl9.eGvKeOjsFgdyjePnevALDfSjLiuhrzC_R6m_JYFKhsA

{
    "title" : "This is a Test about session",
    "description" : "Add Session automatically from Session model",
    "type" : "Testing API Article"
}

################################

//Add comment in Article
POST http://localhost:5001/api/article/add_comment
Content-Type: application/json

{
    "articleId" : "6114d5f6c7e3375c7892f2a2",
    "email" : "longnh20072000@gmail.com",
    "text" : "Sủa"
}

################################

//Create new Session with Token have admin role
POST http://localhost:5001/api/session/add_session
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTE0Y2M4YTg5NGQ4NTUxMTAwNDFkNzQiLCJlbWFpbCI6Imx0di45YTIuMjFAZ21haWwuY29tIiwiZmFjdWx0eSI6IklUIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjI4OTI2MjA5LCJleHAiOjE2Mjg5MjgwMDl9.eGvKeOjsFgdyjePnevALDfSjLiuhrzC_R6m_JYFKhsA

{
    "session" : "Winter 2021",
    "startedDate" : "10/1/2021",
    "endedDate" : "12/1/2021",
    "topic" : "Life"
}

################################